### ISSUE TITLE
py.test --pyargs pyftp fails

### ISSUE THREAD

**Issue by johnh2o2** [PrincetonUniversity/FastTemplatePeriodogram#11]
Hi @jakevdp, I signed into Travis and ran the first test, but the build failed with this error message:

```
0.41s$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    requires=['numpy', 'scipy', 'pynfft', 'gatspy', 'astroML', 'scikit-learn'],
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/dist.py", line 318, in __init__
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/distutils/dist.py", line 253, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/distutils/dist.py", line 1208, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/home/travis/miniconda/envs/test-env/lib/python3.5/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-learn'
The command "python setup.py install" failed and exited with 1 during .
Your build has been stopped.
```

I fixed this problem by changing `scikit-learn` to `sklearn`. However, Travis then reports that `py.test` fails to find the `pyftp` package:

```
0.45s$ python setup.py install
running install
running bdist_egg
running egg_info
creating pyftp.egg-info
writing pyftp.egg-info/PKG-INFO
writing top-level names to pyftp.egg-info/top_level.txt
writing dependency_links to pyftp.egg-info/dependency_links.txt
writing manifest file 'pyftp.egg-info/SOURCES.txt'
reading manifest file 'pyftp.egg-info/SOURCES.txt'
writing manifest file 'pyftp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pyftp
copying ./pyftp/__init__.py -> build/lib/pyftp
copying ./pyftp/fast_template_periodogram.py -> build/lib/pyftp
copying ./pyftp/gatspy_template_modeler.py -> build/lib/pyftp
copying ./pyftp/modeler.py -> build/lib/pyftp
copying ./pyftp/pseudo_poly.py -> build/lib/pyftp
copying ./pyftp/rrlyrae.py -> build/lib/pyftp
copying ./pyftp/utils.py -> build/lib/pyftp
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/__init__.py -> build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/fast_template_periodogram.py -> build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/gatspy_template_modeler.py -> build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/modeler.py -> build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/pseudo_poly.py -> build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/rrlyrae.py -> build/bdist.linux-x86_64/egg/pyftp
copying build/lib/pyftp/utils.py -> build/bdist.linux-x86_64/egg/pyftp
byte-compiling build/bdist.linux-x86_64/egg/pyftp/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyftp/fast_template_periodogram.py to fast_template_periodogram.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyftp/gatspy_template_modeler.py to gatspy_template_modeler.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyftp/modeler.py to modeler.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyftp/pseudo_poly.py to pseudo_poly.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyftp/rrlyrae.py to rrlyrae.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyftp/utils.py to utils.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyftp.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyftp.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyftp.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyftp.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pyftp-0.3.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyftp-0.3.0-py2.7.egg
Copying pyftp-0.3.0-py2.7.egg to /home/travis/miniconda/envs/test-env/lib/python2.7/site-packages
Adding pyftp 0.3.0 to easy-install.pth file
Installed /home/travis/miniconda/envs/test-env/lib/python2.7/site-packages/pyftp-0.3.0-py2.7.egg
Processing dependencies for pyftp==0.3.0
Finished processing dependencies for pyftp==0.3.0
0.01s$ mkdir -p $TEST_DIR
The command "mkdir -p $TEST_DIR" exited with 0.
0.39s$ cd $TEST_DIR && py.test --pyargs pyftp
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /tmp/pyftp, inifile: 
========================= no tests ran in 0.00 seconds =========================
ERROR: file or package not found: pyftp (missing __init__.py?)
The command "cd $TEST_DIR && py.test --pyargs pyftp" exited with 4.
Done. Your build exited with 1.
```
I have reproduced this problem on my machine. This may be related to this Conda problem:
https://github.com/conda/conda/issues/2075

To test that, I made a `setup.cfg` file and set
```cfg
[easy_install]
zip_ok = False
```
and ran
```
[jah5@macpro:testing]$ py.test --pyargs pyftp
============================================================ test session starts =============================================================
platform darwin -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /Users/jah5/Documents/projects/fast_template_periodogram/testing, inifile:
collected 0 items

======================================================== no tests ran in 0.01 seconds ========================================================
```

from my own testing directory (`../testing`). Any ideas for what the problem might be?

**Comment by jakevdp** [comment]
Fixed in #10
